# Este ficheiro agora é responsável APENAS por iniciar o banco de dados.
# O backend e o frontend serão executados localmente ("na mão").

services:
  db: # O serviço do banco de dados
    image: postgres:15-alpine
    container_name: meu_projeto_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # Mapeia a porta 5432 do contentor para a porta 5432 da sua máquina
      # para que o seu backend local se possa ligar a ele.
      - "5432:5432"

volumes:
  postgres_data: